// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tripora.DestinationService.Data;

#nullable disable

namespace Tripora.DestinationService.Migrations
{
    [DbContext(typeof(DestinationDbContext))]
    [Migration("20260912084411_SeedInitialDestinationsData")]
    partial class SeedInitialDestinationsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tripora.DestinationService.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AvailableRooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Location");

                    b.HasIndex("PricePerNight");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Amenities = "Ocean View, Private Pool, Free WiFi, Spa, Breakfast Included, Airport Shuttle",
                            AvailableRooms = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Overwater luxury villas featuring direct lagoon access, sunset infinity pools, and world-class fine dining.",
                            ImageUrl = "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Location = "South Malé Atoll, Maldives",
                            Name = "The Azure Horizon Resort",
                            PricePerNight = 420.00m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Amenities = "Ski-in/Ski-out, Spa & Sauna, Free WiFi, Mountain View, Restaurant, Bar",
                            AvailableRooms = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cozy alpine chalet-style architecture offering panoramic Matterhorn views, heated thermal baths, and fireside lounges.",
                            ImageUrl = "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Location = "Zermatt, Switzerland",
                            Name = "Grand Alpine Sanctuary",
                            PricePerNight = 290.00m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Amenities = "Metro Access, Fitness Center, High-Speed WiFi, Room Service, Business Lounge",
                            AvailableRooms = 50,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sleek contemporary rooms right in the vibrant heart of the city, steps away from transit lines and premier dining.",
                            ImageUrl = "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Location = "Tokyo, Japan",
                            Name = "The Imperial Palace Hotel",
                            PricePerNight = 195.00m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Amenities = "Sea Balcony, Complimentary Breakfast, Free WiFi, Concierge, Valet Parking",
                            AvailableRooms = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant cliff-perched boutique accommodation featuring terraced lemon gardens and panoramic Mediterranean seascapes.",
                            ImageUrl = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Location = "Amalfi Coast, Italy",
                            Name = "Villa Positano Cliffside",
                            PricePerNight = 360.00m,
                            Rating = 5.0
                        });
                });

            modelBuilder.Entity("Tripora.DestinationService.Models.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Destination");

                    b.HasIndex("IsActive");

                    b.HasIndex("Price");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AvailableSlots = 20,
                            Capacity = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hike breathtaking Alpine trails, explore ancient ice caves, and experience scenic cogwheel rail journeys through the Jungfrau region.",
                            Destination = "Interlaken, Switzerland",
                            DurationDays = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Name = "Alpine Glacier Explorer",
                            Price = 1250.00m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AvailableSlots = 12,
                            Capacity = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Witness the Great Migration up close with guided off-road drives, luxury tent camps, and panoramic savannah sunsets.",
                            Destination = "Arusha, Tanzania",
                            DurationDays = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Name = "Serengeti Wildlife Safari",
                            Price = 2800.00m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AvailableSlots = 15,
                            Capacity = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stroll through historic bamboo groves, ancient Shinto shrines, and participate in authentic traditional tea ceremonies.",
                            Destination = "Kyoto, Japan",
                            DurationDays = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Name = "Kyoto Cultural Heritage Walk",
                            Price = 890.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AvailableSlots = 10,
                            Capacity = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sail past dramatic cliffside villages, explore hidden coves, and sample authentic regional Mediterranean cuisine.",
                            Destination = "Positano, Italy",
                            DurationDays = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Name = "Amalfi Coastline Cruise",
                            Price = 1750.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
