// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tripora.DestinationService.Data;

#nullable disable

namespace Tripora.DestinationService.Migrations
{
    [DbContext(typeof(DestinationDbContext))]
    [Migration("20260927085549_AddInquiriesTable")]
    partial class AddInquiriesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tripora.DestinationService.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AvailableRooms")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("longblob");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Location");

                    b.HasIndex("PricePerNight");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Amenities = "Infinity Pool, Free WiFi, Spa, Breakfast Included, Restaurant, Airport Shuttle",
                            AvailableRooms = 32,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A luxury eco-resort immersed in forested hills overlooking the ancient landscapes of Sigiriya and Dambulla.",
                            ImageUrl = "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Location = "Sigiriya / Dambulla, Sri Lanka",
                            Name = "Heritance Kandalama",
                            PricePerNight = 180.00m,
                            Rating = 4.7999999999999998,
                            Status = 0,
                            TotalRooms = 32
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Amenities = "Mountain View, Spa, Free WiFi, Breakfast Included, Restaurant, Hiking Trails",
                            AvailableRooms = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A boutique mountain retreat surrounded by tea plantations with sweeping views of Ella's green valleys.",
                            ImageUrl = "https://images.unsplash.com/photo-1582610116397-edb318620f90?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Location = "Ella, Sri Lanka",
                            Name = "98 Acres Resort & Spa",
                            PricePerNight = 220.00m,
                            Rating = 4.9000000000000004,
                            Status = 0,
                            TotalRooms = 24
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Amenities = "Beach Access, Swimming Pool, Free WiFi, Spa, Breakfast Included, Water Sports",
                            AvailableRooms = 48,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A beachfront luxury resort offering tropical gardens, calm ocean views, and effortless coastal living.",
                            ImageUrl = "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Location = "Bentota, Sri Lanka",
                            Name = "Cinnamon Bentota Beach",
                            PricePerNight = 160.00m,
                            Rating = 4.7000000000000002,
                            Status = 0,
                            TotalRooms = 48
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            Amenities = "Heritage Architecture, Courtyard Pool, Free WiFi, Breakfast Included, Restaurant, Concierge",
                            AvailableRooms = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An intimate heritage boutique hotel inside historic Galle Fort, blending colonial character with modern comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Location = "Galle, Sri Lanka",
                            Name = "Galle Fort Hotel",
                            PricePerNight = 140.00m,
                            Rating = 4.5999999999999996,
                            Status = 0,
                            TotalRooms = 14
                        });
                });

            modelBuilder.Entity("Tripora.DestinationService.Models.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("UNREAD")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("inquiries", (string)null);
                });

            modelBuilder.Entity("Tripora.DestinationService.Models.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DiscountPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<decimal>("OfferPriceLKR")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("OriginalPriceLKR")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("SpecialInclusions")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("Category", "IsActive", "StartDate", "EndDate");

                    b.ToTable("Offers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f1b0001-c82e-11f1-ba97-0a0027000001"),
                            BadgeText = "15% OFF SEASON SPECIAL",
                            Category = "Tour",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 15,
                            EndDate = new DateTime(2026, 11, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OfferPriceLKR = 30600.00m,
                            OriginalPriceLKR = 36000.00m,
                            SpecialInclusions = "Complimentary private sunrise breakfast overlooking Nine Arches Bridge",
                            StartDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TargetId = new Guid("8d6d0828-b81e-11f1-ba97-0a002700000b"),
                            Title = "Ella Cloud Forest Rail Odyssey - Seasonal Promo"
                        },
                        new
                        {
                            Id = new Guid("8f1b0002-c82e-11f1-ba97-0a0027000002"),
                            BadgeText = "20% OFF FLASH DEAL",
                            Category = "Package",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercentage = 20,
                            EndDate = new DateTime(2026, 12, 15, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            OfferPriceLKR = 25600.00m,
                            OriginalPriceLKR = 32000.00m,
                            SpecialInclusions = "Free cinnamon island demonstration and spiced tea tasting",
                            StartDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TargetId = new Guid("7a1b0001-c82e-11f1-ba97-0a0027000001"),
                            Title = "Bentota Lagoon Day Out - Group Special"
                        });
                });

            modelBuilder.Entity("Tripora.DestinationService.Models.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AvailableSlots")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("longblob");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Destination");

                    b.HasIndex("IsActive");

                    b.HasIndex("Price");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AvailableSlots = 20,
                            Capacity = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hike breathtaking Alpine trails, explore ancient ice caves, and experience scenic cogwheel rail journeys through the Jungfrau region.",
                            Destination = "Interlaken, Switzerland",
                            DurationDays = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Name = "Alpine Glacier Explorer",
                            Price = 1250.00m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AvailableSlots = 12,
                            Capacity = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Witness the Great Migration up close with guided off-road drives, luxury tent camps, and panoramic savannah sunsets.",
                            Destination = "Arusha, Tanzania",
                            DurationDays = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Name = "Serengeti Wildlife Safari",
                            Price = 2800.00m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AvailableSlots = 15,
                            Capacity = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stroll through historic bamboo groves, ancient Shinto shrines, and participate in authentic traditional tea ceremonies.",
                            Destination = "Kyoto, Japan",
                            DurationDays = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Name = "Kyoto Cultural Heritage Walk",
                            Price = 890.00m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AvailableSlots = 10,
                            Capacity = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sail past dramatic cliffside villages, explore hidden coves, and sample authentic regional Mediterranean cuisine.",
                            Destination = "Positano, Italy",
                            DurationDays = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Name = "Amalfi Coastline Cruise",
                            Price = 1750.00m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Tripora.DestinationService.Models.TravelPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DurationDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("DurationNights")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Inclusions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxGuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("MinGuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PriceLKR")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Destination");

                    b.HasIndex("IsActive");

                    b.HasIndex("PackageType");

                    b.ToTable("TravelPackages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a1b0001-c82e-11f1-ba97-0a0027000001"),
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Private river cruise along Madu Ganga mangrove tunnels, exclusive beach cabana access, and 3-course seafood lunch for couples and families.",
                            Destination = "Bentota, Southern Province",
                            DurationDays = 1,
                            DurationNights = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80",
                            Inclusions = "[\"Private Boat Safari\",\"3-Course Seafood Platter\",\"Beach Cabana Access\",\"Welcome King Coconut\"]",
                            IsActive = true,
                            MaxGuests = 6,
                            MinGuests = 2,
                            Name = "Bentota Luxury Lagoon & Water Villa Private Day Out",
                            PackageType = "DayOut",
                            PriceLKR = 32000.00m
                        },
                        new
                        {
                            Id = new Guid("7a1b0002-c82e-11f1-ba97-0a0027000002"),
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bespoke romantic getaway including private scenic rail pickup, candlelit cliffside tea plantation dinner, and dawn trek to Little Adams Peak.",
                            Destination = "Ella, Central Highlands",
                            DurationDays = 2,
                            DurationNights = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1200&q=80",
                            Inclusions = "[\"First Class Observation Rail\",\"Private Romantic Dinner\",\"Tea Factory Tasting\",\"Chauffeur Guide\"]",
                            IsActive = true,
                            MaxGuests = 2,
                            MinGuests = 2,
                            Name = "Ella Cloud Valley Romantic Couple Escape",
                            PackageType = "CoupleEscape",
                            PriceLKR = 68000.00m
                        },
                        new
                        {
                            Id = new Guid("7a1b0003-c82e-11f1-ba97-0a0027000003"),
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Action-packed white water rafting, canyoning, jungle barbecue, and twilight river bonfire designed for close circles and friend groups.",
                            Destination = "Kitulgala, Sabaragamuwa Province",
                            DurationDays = 1,
                            DurationNights = 0,
                            ImageUrl = "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
                            Inclusions = "[\"Level 4 Rafting Gear \\u0026 Instructor\",\"BBQ Buffet Lunch\",\"Rainforest Trek\",\"GoPro Video Footage\"]",
                            IsActive = true,
                            MaxGuests = 10,
                            MinGuests = 4,
                            Name = "Kitulgala White Water & Rainforest Friends Expedition",
                            PackageType = "FriendsHangout",
                            PriceLKR = 48000.00m
                        },
                        new
                        {
                            Id = new Guid("7a1b0004-c82e-11f1-ba97-0a0027000004"),
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Exclusive 3-day exploration with private 4x4 elephant tracking in Minneriya and sunrise climb to the Sigiriya Citadel with luxury glamping.",
                            Destination = "Sigiriya & Cultural Triangle",
                            DurationDays = 3,
                            DurationNights = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1200&q=80",
                            Inclusions = "[\"Private 4x4 Safari Jeep\",\"All National Park Passes\",\"Luxury Eco Glamping\",\"Dedicated Naturalist\"]",
                            IsActive = true,
                            MaxGuests = 8,
                            MinGuests = 2,
                            Name = "Sigiriya & Minneriya Private Heritage Safari Odyssey",
                            PackageType = "MultiDayTrip",
                            PriceLKR = 115000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
